name: CI/CD
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Clean Install
        run: npm ci
      - name: Build Demo
        run: npm run demo
      - name: Integration Tests
        run: npm run e2e:ci
      - name: Build Distribution
        run: npm run build
      - name: Release
        if: ${{ !env.ACT }}
        run: npx semantic-release@19.0.5 --branches master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
